src/Entity/Photo.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PhotoRepository")
 */
class Photo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string $file
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please, upload an photos first.")
     *
     */
//@Assert\File(mimeTypes={ "photos/png", "photos/jpeg", "photos/jpg" })
    private $file;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $alt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="photos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Album", inversedBy="photos")
     */
    private $album;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $rating;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $original_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile($file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(?string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    public function setAlbum(?Album $album): self
    {
        $this->album = $album;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getOriginalName(): ?string
    {
        return $this->original_name;
    }

    public function setOriginalName(string $original_name): self
    {
        $this->original_name = $original_name;

        return $this;
    }

}

src/Form/PhotoType.php
<?php

namespace App\Form;

use App\Entity\Photo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PhotoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('file', FileType::class, [
                'multiple' => true,
                'attr' => [
                    'accept' => ".jpg,.jpeg,.png"
    ]
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Photo::class,
        ]);
    }
}

templates/photos/add-photo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Uploads TriPhotos{% endblock %}

{% form_theme formPhoto 'bootstrap_4_layout.html.twig' %}

{% block body %}

    <section id="add-photo">
        <div class="container">
            <div class="return">
                <a href="{{ path('home') }}" class="btn btn-warning"><i class="fas fa-home"></i></a>
            </div>
            <h1>Ajoutez des photos</h1>
            <hr>
            <div class="container-form col">
                {{ form_start(formPhoto) }}
                {% if app.user.albums|length != 0 %}
                <div class="form-group">
                    <label for="select-album">Voulez-vous ajouter ces photos à l'un de vos albums ? Si oui, lequel
                        ?</label>
                    <select name="select-album" id="select-album">
                        <option value="" selected>Non</option>
                        {% for album in app.user.albums %}
                            <option value="{{ album.id }}" {% if album.id == albumId %}selected{% endif %}>Album : {{ album.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% else %}
                    <input type="hidden" name="select-album" id="select-album" value="">
                {% endif %}

                <div class="form-group">
                    <label for="photo_file" class="required">Choisissez une ou plusieurs photo(s)<br>
                        <small>(formats acceptés : jpg ou png)</small>
                    </label>
                    {% if errorsFileFormat is defined %}
                        {% for errorFileFormat in errorsFileFormat %}
                            <p class="alert-danger">
                                {{ errorFileFormat }}
                            </p>
                        {% endfor %}
                    {% endif %}
                    {{ form_widget(formPhoto.file) }}
                </div>
                <div class="submit">
                    <button type="submit" class="btn btn-success">Valider</button>
                </div>
                {{ form_end(formPhoto) }}
            </div>

            <p class="tranfert-in-progress">Transfert en cours ...</p>
            <div class="progress">
                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                     aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <p class="percent-progress"></p>
            <div class="lds-roller">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
            <div class="container-links">
                <div class="redirection-links">
                    <a href="{{ path('image_add') }}" class="btn btn-secondary">Ajouter d'autres photos</a>
                    <a href="{{ path('image_all_photos') }}" class="btn btn-info">Voir mes photos</a>
                </div>
            </div>

        </div>
    </section>

{% endblock %}
 {% block javascripts %}
     {{ parent() }}
     <script src="{{ asset('js/progress-bar.js') }}"></script>
 {% endblock %}

templates/photos/all-photos.html.twig
{% extends 'base.html.twig' %}

{% block title %}Toutes mes photos{% endblock %}

{% block body %}

 <section id="all-photos">
     {% include 'partials/flash-messages.html.twig' %}
     <div class="container">
         <h1>Toutes mes photos</h1>
         {% if filter == 0 %}<p>{{ total|length }} photo{% if photos|length > 1 %}s{% endif %}</p>
            {% elseif filter == 1 %} <p>(classées 1 étoile)</p>
                {% elseif filter == 2 %} <p>(classées 2 étoiles)</p>
                    {% elseif filter == 3 %} <p>(classées 3 étoiles)</p>
         {% endif %}
         <div class="container-photos">
             {% for photo in photos %}
                 <div class="container-photo {% if filter != 0 %}{% if photo.rating != filter %}hide{% endif %}{% endif %}">
                     <a href="{{ path('image_one_photo', {'id' :photo.id}) }}" class="link-container-photo">
                         <img src="{{ path('file_download', {'id' :photo.id}) }}" alt="{{ photo.originalName }}">
                     </a>
                     <div class="hover-photo">
                         <p class="original-name"><small>{{ photo.originalName }}</small></p>
                         <a href="{{ path('image_one_photo', {'id' :photo.id}) }}" class="link-photo"></a>
                         <a href="" class="link-send-photo" title="partager cette photo par mail" data-toggle="modal"
                            data-target="#SendFileModalCenter{{ photo.id }}"><i class="fas fa-share-alt"></i></a>
                         <a href="" class="link-erase-photo" title="supprimer cette photo" data-toggle="modal"
                            data-target="#ConfirmationModalCenter{{ photo.id }}"><i
                                     class="far fa-trash-alt"></i></a>
                         <div class="rating">
                             {% set currentPath = path(app.request.attributes.get('_route')) %}
                             <a href="{{ path('image_rating', {'id' :photo.id, 'rating' :1, 'currentPath' :currentPath|trim('/')}) }}" class="{% if photo.rating >= 1 %}active{% endif %}"><i class="fas fa-star"></i></a>
                             <a href="{{ path('image_rating', {'id' :photo.id, 'rating' :2, 'currentPath' :currentPath|trim('/')}) }}" class="{% if photo.rating >= 2 %}active{% endif %}"><i class="fas fa-star"></i></a>
                             <a href="{{ path('image_rating', {'id' :photo.id, 'rating' :3, 'currentPath' :currentPath|trim('/')}) }}" class="{% if photo.rating == 3 %}active{% endif %}"><i class="fas fa-star"></i></a>
                         </div>
                     </div>
                     <div class="loader">
                         <div class="lds-roller">
                             <div></div>
                             <div></div>
                             <div></div>
                             <div></div>
                             <div></div>
                             <div></div>
                             <div></div>
                             <div></div>
                         </div>
                     </div>
                 </div>
                 <div class="modal fade" id="ConfirmationModalCenter{{ photo.id }}" tabindex="-1" role="dialog"
                      aria-labelledby="ModalCenterTitle" aria-hidden="true">
                     <div class="modal-dialog modal-dialog-centered" role="document">
                         <div class="modal-content ConfirmationModal">
                             <div class="modal-header">
                                 <h5 class="modal-title" id="exampleModalLongTitle">Êtes-vous sûr de vouloir
                                     supprimer la photo "{{ photo.originalName }}"</h5>
                                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                     <span aria-hidden="true">&times;</span>
                                 </button>
                             </div>
                             <div class="modal-body">
                                 <a href="" class="btn btn-warning" data-dismiss="modal">Annuler</a>
                                 <a href="{{ path('image_remove_photo', {'id' :photo.id}) }}" class="btn btn-danger"
                                    title="Supprimer cette photo">Supprimer</a>
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="modal fade" id="SendFileModalCenter{{ photo.id }}" tabindex="-1" role="dialog"
                      aria-labelledby="ModalCenterTitle" aria-hidden="true">
                     <div class="modal-dialog modal-dialog-centered" role="document">
                         <div class="modal-content SendFileModal">
                             <div class="modal-header">
                                 <h5 class="modal-title" id="exampleModalLongTitle">Partagez la photo
                                     "{{ photo.originalName }}" par email</h5>
                                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                     <span aria-hidden="true">&times;</span>
                                 </button>
                             </div>
                             <div class="modal-body">
                                 {% set currentPath = 'all-photos' %}
                                 <form action="{{ path('mailer_photo', {'from' :app.user.id, 'photoId' : photo.id, 'currentPath' : currentPath }) }}"
                                       method="post">
                                     <div class="form-group">
                                         <label for="to-email">Adresse email du destinataire :</label>
                                         <input type="email" name="to-email" id="to-email" required="required">
                                     </div>
                                     <div class="form-group">
                                         <label for="content">Message
                                             <small>(facultatif)</small>
                                             :</label>
                                         <textarea name="content" id="content" cols="30" rows="10"></textarea>
                                     </div>
                                     <button class="btn btn-danger" data-dismiss="modal">Annuler</button>
                                     <button class="btn btn-success" type="submit">Envoyer</button>
                                 </form>
                             </div>
                         </div>
                     </div>
                 </div>
             {% endfor %}
         </div>
         {% if total|length > 20 and filter == 0 %}
             {% include 'partials/pagination.html.twig' with {'route': 'image_all_photos'} %}
         {% endif %}
         {% if photos|length >= 1 %}
             <div class="filter">
                 Filtrer :
                 {% if  filter != 0 %}
                     <a href="{{ path('filter_rating', {'rating' :1}) }}"
                        title="Afficher seulement les photos classées 1 étoile" class="{% if filter >= 1 %}active{% endif %}"><i class="fas fa-star"></i></a>
                     <a href="{{ path('filter_rating', {'rating' :2}) }}"
                        title="Afficher seulement les photos classées 2 étoiles" class="{% if filter >= 2 %}active{% endif %}"><i class="fas fa-star"></i></a>
                     <a href="{{ path('filter_rating', {'rating' :3}) }}"
                        title="Afficher seulement les photos classées 3 étoiles" class="{% if filter == 3 %}active{% endif %}"><i class="fas fa-star"></i></a>
                     <a href="{{ path('filter_rating', {'rating' :0}) }}" title="Supprimer le filtre"><i
                                 class="fas fa-filter"></i></a>
                 {% else %}
                     <a href="{{ path('filter_rating', {'rating' :1}) }}"
                        title="Afficher seulement les photos classées 1 étoile"><i
                                 class="fas fa-star"></i></a>
                     <a href="{{ path('filter_rating', {'rating' :2}) }}"
                        title="Afficher seulement les photos classées 2 étoiles"><i
                                 class="fas fa-star"></i></a>
                     <a href="{{ path('filter_rating', {'rating' :3}) }}"
                        title="Afficher seulement les photos classées 3 étoiles"><i
                                 class="fas fa-star"></i></a>
                 {% endif %}
             </div>
         {% endif %}
         <div class="buttons">
             <a class="btn btn-primary" href="{{ path('album_all_albums') }}">Voir mes albums</a>
             <a class="btn btn-secondary" href="{{ path('image_add') }}">Ajouter des photos</a>
         </div>
     </div>
 </section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/rating-stars-hover.js') }}"></script>
{% endblock %}

templates/photos/one-photo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Diaporama Toutes mes photos{% endblock %}

 {% block body %}

<section id="one-photo">
    {% include 'partials/flash-messages.html.twig' %}
    <div class="container">
        <div class="return">
            <a href="{{ path('image_all_photos') }}" class="btn btn-warning"><i class="fas fa-caret-left"></i> Mes photos</a>
        </div>
        <div class="diaporama-header">
            <h1>Diaporama Toutes mes photos</h1>
            <p>{{ allphotos|length }} photo{% if allphotos|length > 1 %}s{% endif %}</p>
        </div>
        <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for userPhotos in allphotos %}
                    <li data-target="#carouselIndicators" data-slide-to="{{ userPhotos.id }}" class="{% if photo.id == userPhotos.id %}active{% endif %}"></li>
                {% endfor %}
            </ol>
            <div class="carousel-inner">
                {% for userPhotos in allphotos %}
                    <div class="carousel-item {% if photo.id == userPhotos.id %}active{% endif %}">
                        <p>{{ userPhotos.originalName }}{% if userPhotos.album is not null %}<i> album "{{ userPhotos.album.title }}"</i>{% endif %}</p>
                        <img src="{{ path('file_download', {'id' :userPhotos.id}) }}" alt="...">
                        <div class="rating">
                            {% set currentPath = 'onePhoto' %}
                            <a href="{{ path('image_rating', {'id' :userPhotos.id, 'rating' :1, 'currentPath' :currentPath}) }}" class="{% if userPhotos.rating >= 1 %}active{% endif %}"><i class="fas fa-star"></i></a>
                            <a href="{{ path('image_rating', {'id' :userPhotos.id, 'rating' :2, 'currentPath' :currentPath}) }}" class="{% if userPhotos.rating >= 2 %}active{% endif %}"><i class="fas fa-star"></i></a>
                            <a href="{{ path('image_rating', {'id' :userPhotos.id, 'rating' :3, 'currentPath' :currentPath}) }}" class="{% if userPhotos.rating == 3 %}active{% endif %}"><i class="fas fa-star"></i></a>
                        </div>
                        <div class="edition">
                            <a href="" class="btn btn-primary" title="déplacer cette photo dans un album" data-toggle="modal" data-target="#ModalCenter{{ userPhotos.id }}"><i class="fas fa-images"></i></a>
                            <a href="" class="btn btn-info" title="partager cette photo par mail" data-toggle="modal" data-target="#SendFileModalCenter{{ userPhotos.id }}"><i class="fas fa-share-alt"></i></a>
                            <a href="" class="btn btn-danger" title="Supprimer cette photo" data-toggle="modal" data-target="#ConfirmationModalCenter{{ userPhotos.id }}"><i class="far fa-trash-alt"></i></a>
                        </div>
                    </div>
                    <div class="modal fade" id="ModalCenter{{ userPhotos.id }}" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Déplacer la photo "{{ userPhotos.originalName }}"</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {% if userPhotos.album is not null %}
                                        <p>Cette photo est classée dans l'album "{{ userPhotos.album.title }}"</p>
                                    {% else %}
                                        <p>Cette photo n'est pas encore classée dans un album</p>
                                    {% endif %}
                                    <form action="{{ path('image_add_to_album', {'photoId' :userPhotos.id }) }}" method="post">
                                        <div class="input-group">
                                            <select name="select-album" id="select-album" class="custom-select" required>
                                                <option value="" disabled selected>Choisissez l'un de vos albums : </option>
                                                {% for album in albums %}
                                                    <option value="{{ album.id }}" {% if userPhotos.album is not null %}{% if album.id == userPhotos.album.id %}disabled{% endif %}{% endif %}>{{ album.title }}</option>
                                                {% endfor %}
                                                <option value="null" {% if userPhotos.album is null %}disabled{% endif %}>Aucun (déclasser cette photo)</option>
                                            </select>
                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-success">Valider</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal fade" id="SendFileModalCenter{{ userPhotos.id }}" tabindex="-1" role="dialog"
                         aria-labelledby="ModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content SendFileModal">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Partagez la photo
                                        "{{ userPhotos.originalName }}" par email</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {% set currentPath = 'one-photos' %}
                                    <form action="{{ path('mailer_photo', {'from' :app.user.id, 'photoId' : userPhotos.id, 'currentPath' : currentPath }) }}"
                                          method="post">
                                        <div class="form-group">
                                            <label for="to-email">Adresse email du destinataire :</label>
                                            <input type="email" name="to-email" id="to-email" required="required">
                                        </div>
                                        <div class="form-group">
                                            <label for="content">Message
                                                <small>(facultatif)</small>
                                                :</label>
                                            <textarea name="content" id="content" cols="30" rows="10"></textarea>
                                        </div>
                                        <button class="btn btn-danger" data-dismiss="modal">Annuler</button>
                                        <button class="btn btn-success" type="submit">Envoyer</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal fade" id="ConfirmationModalCenter{{ userPhotos.id }}" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Êtes-vous sûr de vouloir supprimer la photo "{{ userPhotos.originalName }}"</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <button type="button" class="btn btn-warning" data-dismiss="modal">Annuler</button>
                                    <a href="{{ path('image_remove_photo', {'id' :userPhotos.id, 'currentPath' :currentPath}) }}" class="btn btn-danger" title="Supprimer cette photo">Supprimer</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</section>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/rating-stars-hover.js') }}"></script>
{% endblock %}